/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOiArduBotScopeProvider extends DelegatingScopeProvider {
}
