/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link OiArdubotWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractOiArdubotWebModule extends DefaultWebModule {

}
