/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.web;

import br.edu.utfpr.oiardubot.OiArdubotRuntimeModule;
import br.edu.utfpr.oiardubot.OiArdubotStandaloneSetup;
import br.edu.utfpr.oiardubot.ide.OiArdubotIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class OiArdubotWebSetup extends OiArdubotStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OiArdubotRuntimeModule(), new OiArdubotIdeModule(), new OiArdubotWebModule()));
	}
	
}
