/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class OiArdubotWebModule extends AbstractOiArdubotWebModule {
}
