/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enquanto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Enquanto#getValorEsquerda <em>Valor Esquerda</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Enquanto#getRelacao <em>Relacao</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Enquanto#getValorDireita <em>Valor Direita</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Enquanto#getCode <em>Code</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getEnquanto()
 * @model
 * @generated
 */
public interface Enquanto extends Implementacao
{
  /**
   * Returns the value of the '<em><b>Valor Esquerda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor Esquerda</em>' attribute.
   * @see #setValorEsquerda(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getEnquanto_ValorEsquerda()
   * @model
   * @generated
   */
  String getValorEsquerda();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Enquanto#getValorEsquerda <em>Valor Esquerda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor Esquerda</em>' attribute.
   * @see #getValorEsquerda()
   * @generated
   */
  void setValorEsquerda(String value);

  /**
   * Returns the value of the '<em><b>Relacao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relacao</em>' containment reference.
   * @see #setRelacao(Logico)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getEnquanto_Relacao()
   * @model containment="true"
   * @generated
   */
  Logico getRelacao();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Enquanto#getRelacao <em>Relacao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relacao</em>' containment reference.
   * @see #getRelacao()
   * @generated
   */
  void setRelacao(Logico value);

  /**
   * Returns the value of the '<em><b>Valor Direita</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor Direita</em>' attribute.
   * @see #setValorDireita(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getEnquanto_ValorDireita()
   * @model
   * @generated
   */
  String getValorDireita();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Enquanto#getValorDireita <em>Valor Direita</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor Direita</em>' attribute.
   * @see #getValorDireita()
   * @generated
   */
  void setValorDireita(String value);

  /**
   * Returns the value of the '<em><b>Code</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.oiardubot.oiArdubot.Implementacao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code</em>' containment reference list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getEnquanto_Code()
   * @model containment="true"
   * @generated
   */
  EList<Implementacao> getCode();

} // Enquanto
