/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Escolha</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Escolha#getValor <em>Valor</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Escolha#getCasos <em>Casos</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getEscolha()
 * @model
 * @generated
 */
public interface Escolha extends Implementacao
{
  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getEscolha_Valor()
   * @model
   * @generated
   */
  String getValor();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Escolha#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(String value);

  /**
   * Returns the value of the '<em><b>Casos</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.oiardubot.oiArdubot.Caso}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Casos</em>' containment reference list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getEscolha_Casos()
   * @model containment="true"
   * @generated
   */
  EList<Caso> getCasos();

} // Escolha
