/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Funcao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getName <em>Name</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getParametro <em>Parametro</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getTipo <em>Tipo</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getCodigo <em>Codigo</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getRetorno <em>Retorno</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getFuncao()
 * @model
 * @generated
 */
public interface Funcao extends Implementacao
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getFuncao_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parametro</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametro</em>' containment reference.
   * @see #setParametro(Parametro)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getFuncao_Parametro()
   * @model containment="true"
   * @generated
   */
  Parametro getParametro();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getParametro <em>Parametro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parametro</em>' containment reference.
   * @see #getParametro()
   * @generated
   */
  void setParametro(Parametro value);

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * The literals are from the enumeration {@link br.edu.utfpr.oiardubot.oiArdubot.Tipo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see br.edu.utfpr.oiardubot.oiArdubot.Tipo
   * @see #setTipo(Tipo)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getFuncao_Tipo()
   * @model
   * @generated
   */
  Tipo getTipo();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see br.edu.utfpr.oiardubot.oiArdubot.Tipo
   * @see #getTipo()
   * @generated
   */
  void setTipo(Tipo value);

  /**
   * Returns the value of the '<em><b>Codigo</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.oiardubot.oiArdubot.Implementacao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Codigo</em>' containment reference list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getFuncao_Codigo()
   * @model containment="true"
   * @generated
   */
  EList<Implementacao> getCodigo();

  /**
   * Returns the value of the '<em><b>Retorno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retorno</em>' attribute.
   * @see #setRetorno(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getFuncao_Retorno()
   * @model
   * @generated
   */
  String getRetorno();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Funcao#getRetorno <em>Retorno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Retorno</em>' attribute.
   * @see #getRetorno()
   * @generated
   */
  void setRetorno(String value);

} // Funcao
