/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Model#getVar <em>Var</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Model#getVariaveis <em>Variaveis</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Model#getConstantes <em>Constantes</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Model#getIni <em>Ini</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Model#getCodigo <em>Codigo</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Model#getFim <em>Fim</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getModel_Var()
   * @model unique="false"
   * @generated
   */
  EList<String> getVar();

  /**
   * Returns the value of the '<em><b>Variaveis</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.oiardubot.oiArdubot.Variavel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variaveis</em>' containment reference list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getModel_Variaveis()
   * @model containment="true"
   * @generated
   */
  EList<Variavel> getVariaveis();

  /**
   * Returns the value of the '<em><b>Constantes</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.oiardubot.oiArdubot.Constante}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constantes</em>' containment reference list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getModel_Constantes()
   * @model containment="true"
   * @generated
   */
  EList<Constante> getConstantes();

  /**
   * Returns the value of the '<em><b>Ini</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ini</em>' attribute list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getModel_Ini()
   * @model unique="false"
   * @generated
   */
  EList<String> getIni();

  /**
   * Returns the value of the '<em><b>Codigo</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.oiardubot.oiArdubot.Implementacao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Codigo</em>' containment reference list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getModel_Codigo()
   * @model containment="true"
   * @generated
   */
  EList<Implementacao> getCodigo();

  /**
   * Returns the value of the '<em><b>Fim</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fim</em>' attribute list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getModel_Fim()
   * @model unique="false"
   * @generated
   */
  EList<String> getFim();

} // Model
