/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Motor DC</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.MotorDC#getEstado <em>Estado</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.MotorDC#getDirecao <em>Direcao</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getMotorDC()
 * @model
 * @generated
 */
public interface MotorDC extends Implementacao
{
  /**
   * Returns the value of the '<em><b>Estado</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Estado</em>' attribute.
   * @see #setEstado(int)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getMotorDC_Estado()
   * @model
   * @generated
   */
  int getEstado();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.MotorDC#getEstado <em>Estado</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Estado</em>' attribute.
   * @see #getEstado()
   * @generated
   */
  void setEstado(int value);

  /**
   * Returns the value of the '<em><b>Direcao</b></em>' attribute.
   * The literals are from the enumeration {@link br.edu.utfpr.oiardubot.oiArdubot.Direcao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direcao</em>' attribute.
   * @see br.edu.utfpr.oiardubot.oiArdubot.Direcao
   * @see #setDirecao(Direcao)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getMotorDC_Direcao()
   * @model
   * @generated
   */
  Direcao getDirecao();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.MotorDC#getDirecao <em>Direcao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direcao</em>' attribute.
   * @see br.edu.utfpr.oiardubot.oiArdubot.Direcao
   * @see #getDirecao()
   * @generated
   */
  void setDirecao(Direcao value);

} // MotorDC
