/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage
 * @generated
 */
public interface OiArdubotFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OiArdubotFactory eINSTANCE = br.edu.utfpr.oiardubot.oiArdubot.impl.OiArdubotFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Codigo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Codigo</em>'.
   * @generated
   */
  Codigo createCodigo();

  /**
   * Returns a new object of class '<em>Implementacao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Implementacao</em>'.
   * @generated
   */
  Implementacao createImplementacao();

  /**
   * Returns a new object of class '<em>Porta</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Porta</em>'.
   * @generated
   */
  Porta createPorta();

  /**
   * Returns a new object of class '<em>Porta Analogica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Porta Analogica</em>'.
   * @generated
   */
  PortaAnalogica createPortaAnalogica();

  /**
   * Returns a new object of class '<em>Porta Digital</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Porta Digital</em>'.
   * @generated
   */
  PortaDigital createPortaDigital();

  /**
   * Returns a new object of class '<em>Receber Valor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Receber Valor</em>'.
   * @generated
   */
  ReceberValor createReceberValor();

  /**
   * Returns a new object of class '<em>Existente Variavel Recebe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Existente Variavel Recebe</em>'.
   * @generated
   */
  ExistenteVariavelRecebe createExistenteVariavelRecebe();

  /**
   * Returns a new object of class '<em>Nova Variavel Recebe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nova Variavel Recebe</em>'.
   * @generated
   */
  NovaVariavelRecebe createNovaVariavelRecebe();

  /**
   * Returns a new object of class '<em>Variavel Nome</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variavel Nome</em>'.
   * @generated
   */
  VariavelNome createVariavelNome();

  /**
   * Returns a new object of class '<em>Variavel Ou Porta</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variavel Ou Porta</em>'.
   * @generated
   */
  VariavelOuPorta createVariavelOuPorta();

  /**
   * Returns a new object of class '<em>Nome</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nome</em>'.
   * @generated
   */
  Nome createNome();

  /**
   * Returns a new object of class '<em>Conteudo Escrever</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conteudo Escrever</em>'.
   * @generated
   */
  ConteudoEscrever createConteudoEscrever();

  /**
   * Returns a new object of class '<em>Texto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Texto</em>'.
   * @generated
   */
  Texto createTexto();

  /**
   * Returns a new object of class '<em>Inteiro</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inteiro</em>'.
   * @generated
   */
  Inteiro createInteiro();

  /**
   * Returns a new object of class '<em>Variavel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variavel</em>'.
   * @generated
   */
  Variavel createVariavel();

  /**
   * Returns a new object of class '<em>Variavel Existente</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variavel Existente</em>'.
   * @generated
   */
  VariavelExistente createVariavelExistente();

  /**
   * Returns a new object of class '<em>Constante Variavel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constante Variavel</em>'.
   * @generated
   */
  ConstanteVariavel createConstanteVariavel();

  /**
   * Returns a new object of class '<em>Constante</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constante</em>'.
   * @generated
   */
  Constante createConstante();

  /**
   * Returns a new object of class '<em>Controle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Controle</em>'.
   * @generated
   */
  Controle createControle();

  /**
   * Returns a new object of class '<em>Logico</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logico</em>'.
   * @generated
   */
  Logico createLogico();

  /**
   * Returns a new object of class '<em>Ler</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ler</em>'.
   * @generated
   */
  Ler createLer();

  /**
   * Returns a new object of class '<em>Ler Digital</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ler Digital</em>'.
   * @generated
   */
  LerDigital createLerDigital();

  /**
   * Returns a new object of class '<em>Funcao Ler Digital</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Funcao Ler Digital</em>'.
   * @generated
   */
  FuncaoLerDigital createFuncaoLerDigital();

  /**
   * Returns a new object of class '<em>Ler Analogica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ler Analogica</em>'.
   * @generated
   */
  LerAnalogica createLerAnalogica();

  /**
   * Returns a new object of class '<em>Funcao Ler Analogica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Funcao Ler Analogica</em>'.
   * @generated
   */
  FuncaoLerAnalogica createFuncaoLerAnalogica();

  /**
   * Returns a new object of class '<em>Escrever</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Escrever</em>'.
   * @generated
   */
  Escrever createEscrever();

  /**
   * Returns a new object of class '<em>Tela</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tela</em>'.
   * @generated
   */
  Tela createTela();

  /**
   * Returns a new object of class '<em>Bip</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bip</em>'.
   * @generated
   */
  Bip createBip();

  /**
   * Returns a new object of class '<em>Ligar</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligar</em>'.
   * @generated
   */
  Ligar createLigar();

  /**
   * Returns a new object of class '<em>Desligar</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Desligar</em>'.
   * @generated
   */
  Desligar createDesligar();

  /**
   * Returns a new object of class '<em>Servo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Servo</em>'.
   * @generated
   */
  Servo createServo();

  /**
   * Returns a new object of class '<em>Motor DC</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Motor DC</em>'.
   * @generated
   */
  MotorDC createMotorDC();

  /**
   * Returns a new object of class '<em>Andar</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Andar</em>'.
   * @generated
   */
  Andar createAndar();

  /**
   * Returns a new object of class '<em>Parar</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parar</em>'.
   * @generated
   */
  Parar createParar();

  /**
   * Returns a new object of class '<em>Para</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Para</em>'.
   * @generated
   */
  Para createPara();

  /**
   * Returns a new object of class '<em>Fim Para</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fim Para</em>'.
   * @generated
   */
  FimPara createFimPara();

  /**
   * Returns a new object of class '<em>Enquanto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enquanto</em>'.
   * @generated
   */
  Enquanto createEnquanto();

  /**
   * Returns a new object of class '<em>Repita</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Repita</em>'.
   * @generated
   */
  Repita createRepita();

  /**
   * Returns a new object of class '<em>Se</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Se</em>'.
   * @generated
   */
  Se createSe();

  /**
   * Returns a new object of class '<em>Fimse</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fimse</em>'.
   * @generated
   */
  Fimse createFimse();

  /**
   * Returns a new object of class '<em>Senao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Senao</em>'.
   * @generated
   */
  Senao createSenao();

  /**
   * Returns a new object of class '<em>Escolha</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Escolha</em>'.
   * @generated
   */
  Escolha createEscolha();

  /**
   * Returns a new object of class '<em>Caso</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Caso</em>'.
   * @generated
   */
  Caso createCaso();

  /**
   * Returns a new object of class '<em>Funcao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Funcao</em>'.
   * @generated
   */
  Funcao createFuncao();

  /**
   * Returns a new object of class '<em>Parametro</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parametro</em>'.
   * @generated
   */
  Parametro createParametro();

  /**
   * Returns a new object of class '<em>Espera</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Espera</em>'.
   * @generated
   */
  Espera createEspera();

  /**
   * Returns a new object of class '<em>Soma</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Soma</em>'.
   * @generated
   */
  Soma createSoma();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  OiArdubotPackage getOiArdubotPackage();

} //OiArdubotFactory
