/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parar</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Parar#getPorta <em>Porta</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getParar()
 * @model
 * @generated
 */
public interface Parar extends Implementacao
{
  /**
   * Returns the value of the '<em><b>Porta</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Porta</em>' containment reference.
   * @see #setPorta(Porta)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getParar_Porta()
   * @model containment="true"
   * @generated
   */
  Porta getPorta();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Parar#getPorta <em>Porta</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Porta</em>' containment reference.
   * @see #getPorta()
   * @generated
   */
  void setPorta(Porta value);

} // Parar
