/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Se</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getValorEsquerda <em>Valor Esquerda</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getRelacao <em>Relacao</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getValorDireita <em>Valor Direita</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getCode <em>Code</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getSenao <em>Senao</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getFimse <em>Fimse</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getSe()
 * @model
 * @generated
 */
public interface Se extends Implementacao
{
  /**
   * Returns the value of the '<em><b>Valor Esquerda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor Esquerda</em>' attribute.
   * @see #setValorEsquerda(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getSe_ValorEsquerda()
   * @model
   * @generated
   */
  String getValorEsquerda();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getValorEsquerda <em>Valor Esquerda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor Esquerda</em>' attribute.
   * @see #getValorEsquerda()
   * @generated
   */
  void setValorEsquerda(String value);

  /**
   * Returns the value of the '<em><b>Relacao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relacao</em>' containment reference.
   * @see #setRelacao(Logico)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getSe_Relacao()
   * @model containment="true"
   * @generated
   */
  Logico getRelacao();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getRelacao <em>Relacao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relacao</em>' containment reference.
   * @see #getRelacao()
   * @generated
   */
  void setRelacao(Logico value);

  /**
   * Returns the value of the '<em><b>Valor Direita</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor Direita</em>' attribute.
   * @see #setValorDireita(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getSe_ValorDireita()
   * @model
   * @generated
   */
  String getValorDireita();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getValorDireita <em>Valor Direita</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor Direita</em>' attribute.
   * @see #getValorDireita()
   * @generated
   */
  void setValorDireita(String value);

  /**
   * Returns the value of the '<em><b>Code</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.oiardubot.oiArdubot.Implementacao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code</em>' containment reference list.
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getSe_Code()
   * @model containment="true"
   * @generated
   */
  EList<Implementacao> getCode();

  /**
   * Returns the value of the '<em><b>Senao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Senao</em>' containment reference.
   * @see #setSenao(Senao)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getSe_Senao()
   * @model containment="true"
   * @generated
   */
  Senao getSenao();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getSenao <em>Senao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Senao</em>' containment reference.
   * @see #getSenao()
   * @generated
   */
  void setSenao(Senao value);

  /**
   * Returns the value of the '<em><b>Fimse</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fimse</em>' containment reference.
   * @see #setFimse(Fimse)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getSe_Fimse()
   * @model containment="true"
   * @generated
   */
  Fimse getFimse();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Se#getFimse <em>Fimse</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fimse</em>' containment reference.
   * @see #getFimse()
   * @generated
   */
  void setFimse(Fimse value);

} // Se
