/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tela</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Tela#getMensagem <em>Mensagem</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getTela()
 * @model
 * @generated
 */
public interface Tela extends Implementacao
{
  /**
   * Returns the value of the '<em><b>Mensagem</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mensagem</em>' attribute.
   * @see #setMensagem(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getTela_Mensagem()
   * @model
   * @generated
   */
  String getMensagem();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Tela#getMensagem <em>Mensagem</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mensagem</em>' attribute.
   * @see #getMensagem()
   * @generated
   */
  void setMensagem(String value);

} // Tela
