/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variavel Existente</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.VariavelExistente#getAtribuicao <em>Atribuicao</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.VariavelExistente#getValor <em>Valor</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavelExistente()
 * @model
 * @generated
 */
public interface VariavelExistente extends Implementacao
{
  /**
   * Returns the value of the '<em><b>Atribuicao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atribuicao</em>' containment reference.
   * @see #setAtribuicao(ExistenteVariavelRecebe)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavelExistente_Atribuicao()
   * @model containment="true"
   * @generated
   */
  ExistenteVariavelRecebe getAtribuicao();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.VariavelExistente#getAtribuicao <em>Atribuicao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atribuicao</em>' containment reference.
   * @see #getAtribuicao()
   * @generated
   */
  void setAtribuicao(ExistenteVariavelRecebe value);

  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavelExistente_Valor()
   * @model
   * @generated
   */
  String getValor();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.VariavelExistente#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(String value);

} // VariavelExistente
