/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variavel Nome</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.VariavelNome#getTipo <em>Tipo</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.VariavelNome#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavelNome()
 * @model
 * @generated
 */
public interface VariavelNome extends NovaVariavelRecebe
{
  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * The literals are from the enumeration {@link br.edu.utfpr.oiardubot.oiArdubot.Tipo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see br.edu.utfpr.oiardubot.oiArdubot.Tipo
   * @see #setTipo(Tipo)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavelNome_Tipo()
   * @model
   * @generated
   */
  Tipo getTipo();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.VariavelNome#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see br.edu.utfpr.oiardubot.oiArdubot.Tipo
   * @see #getTipo()
   * @generated
   */
  void setTipo(Tipo value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavelNome_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.VariavelNome#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // VariavelNome
