/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variavel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Variavel#getVariavelNome <em>Variavel Nome</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.Variavel#getValor <em>Valor</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavel()
 * @model
 * @generated
 */
public interface Variavel extends EObject
{
  /**
   * Returns the value of the '<em><b>Variavel Nome</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variavel Nome</em>' containment reference.
   * @see #setVariavelNome(VariavelNome)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavel_VariavelNome()
   * @model containment="true"
   * @generated
   */
  VariavelNome getVariavelNome();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Variavel#getVariavelNome <em>Variavel Nome</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variavel Nome</em>' containment reference.
   * @see #getVariavelNome()
   * @generated
   */
  void setVariavelNome(VariavelNome value);

  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(String)
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#getVariavel_Valor()
   * @model
   * @generated
   */
  String getValor();

  /**
   * Sets the value of the '{@link br.edu.utfpr.oiardubot.oiArdubot.Variavel#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(String value);

} // Variavel
