/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class OiArduBotProposalProvider extends AbstractOiArduBotProposalProvider {
}
