/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.ui;

import br.edu.utfpr.oiardubot.ui.internal.OiardubotActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OiArdubotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(OiardubotActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		OiardubotActivator activator = OiardubotActivator.getInstance();
		return activator != null ? activator.getInjector(OiardubotActivator.BR_EDU_UTFPR_OIARDUBOT_OIARDUBOT) : null;
	}

}
