<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OiArduBot" nsURI="http://fb.utfpr.edu.br/OiArduBot" nsPrefix="OiArduBot">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codigo" upperBound="-1"
        eType="#//Codigo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variavel" upperBound="-1"
        eType="#//Variavel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="funcao" upperBound="-1"
        eType="#//Funcao" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Codigo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iteracao" upperBound="-1"
        eType="#//Iteracao" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controle" upperBound="-1"
        eType="#//Controle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="robo" upperBound="-1" eType="#//Robo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variavel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="#//Tipo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atuacao" upperBound="-1"
        eType="#//Atuacao" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensoriamento" upperBound="-1"
        eType="#//Sensoriamento" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="se" upperBound="-1" eType="#//Se"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="escolha" upperBound="-1"
        eType="#//Escolha" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iteracao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="para" upperBound="-1" eType="#//Para"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enquanto" upperBound="-1"
        eType="#//Enquanto" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repita" upperBound="-1"
        eType="#//Repita" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensoriamento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="porta" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoPorta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atuacao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="movimento" upperBound="-1"
        eType="#//Movimento" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notificacao" upperBound="-1"
        eType="#//Notificacao" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Funcao">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parametro" upperBound="3"
        eType="#//Tipo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Tipo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Notificacao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beep" upperBound="-1" eType="#//Beep"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="display" upperBound="-1"
        eType="#//Display" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="led" upperBound="-1" eType="#//Ligar"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Movimento">
    <eStructuralFeatures xsi:type="ecore:EReference" name="motordc" upperBound="-1"
        eType="#//MotorDC" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servo" upperBound="-1"
        eType="#//Servo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Servo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="posicao" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotorDC">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="motor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="velocitade" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sentido" eType="#//Sentido"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ligar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ligar" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="porta" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Display">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mensagem" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Se">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condicao" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="senao" upperBound="-1"
        eType="#//Senao" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Escolha">
    <eStructuralFeatures xsi:type="ecore:EReference" name="caso" lowerBound="1" upperBound="-1"
        eType="#//Caso" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Para">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="de" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ate" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passo" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enquanto">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condicao" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repita">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Caso">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Senao"/>
  <eClassifiers xsi:type="ecore:EClass" name="Beep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoBeep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Sentido"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoBeep"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoPorta"/>
</ecore:EPackage>
