<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codigo" upperBound="-1"
        eType="#//Codigo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variavel" upperBound="-1"
        eType="#//Variavel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Codigo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variavel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Codigo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robo" upperBound="-1" eType="#//Robo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controle" upperBound="-1"
        eType="#//Controle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iteracao" upperBound="-1"
        eType="#//Iteracao" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Controle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Iteracao"/>
</ecore:EPackage>
