/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot.impl;

import br.edu.utfpr.oiardubot.oiArdubot.Funcao;
import br.edu.utfpr.oiardubot.oiArdubot.Implementacao;
import br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage;
import br.edu.utfpr.oiardubot.oiArdubot.Parametro;
import br.edu.utfpr.oiardubot.oiArdubot.Tipo;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Funcao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.FuncaoImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.FuncaoImpl#getParametro <em>Parametro</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.FuncaoImpl#getTipo <em>Tipo</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.FuncaoImpl#getCodigo <em>Codigo</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.FuncaoImpl#getRetorno <em>Retorno</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FuncaoImpl extends ImplementacaoImpl implements Funcao
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParametro() <em>Parametro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParametro()
   * @generated
   * @ordered
   */
  protected Parametro parametro;

  /**
   * The default value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected static final Tipo TIPO_EDEFAULT = Tipo.TEXTO;

  /**
   * The cached value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected Tipo tipo = TIPO_EDEFAULT;

  /**
   * The cached value of the '{@link #getCodigo() <em>Codigo</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodigo()
   * @generated
   * @ordered
   */
  protected EList<Implementacao> codigo;

  /**
   * The default value of the '{@link #getRetorno() <em>Retorno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRetorno()
   * @generated
   * @ordered
   */
  protected static final String RETORNO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRetorno() <em>Retorno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRetorno()
   * @generated
   * @ordered
   */
  protected String retorno = RETORNO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OiArdubotPackage.Literals.FUNCAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.FUNCAO__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Parametro getParametro()
  {
    return parametro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParametro(Parametro newParametro, NotificationChain msgs)
  {
    Parametro oldParametro = parametro;
    parametro = newParametro;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OiArdubotPackage.FUNCAO__PARAMETRO, oldParametro, newParametro);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParametro(Parametro newParametro)
  {
    if (newParametro != parametro)
    {
      NotificationChain msgs = null;
      if (parametro != null)
        msgs = ((InternalEObject)parametro).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.FUNCAO__PARAMETRO, null, msgs);
      if (newParametro != null)
        msgs = ((InternalEObject)newParametro).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.FUNCAO__PARAMETRO, null, msgs);
      msgs = basicSetParametro(newParametro, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.FUNCAO__PARAMETRO, newParametro, newParametro));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Tipo getTipo()
  {
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipo(Tipo newTipo)
  {
    Tipo oldTipo = tipo;
    tipo = newTipo == null ? TIPO_EDEFAULT : newTipo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.FUNCAO__TIPO, oldTipo, tipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Implementacao> getCodigo()
  {
    if (codigo == null)
    {
      codigo = new EObjectContainmentEList<Implementacao>(Implementacao.class, this, OiArdubotPackage.FUNCAO__CODIGO);
    }
    return codigo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRetorno()
  {
    return retorno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRetorno(String newRetorno)
  {
    String oldRetorno = retorno;
    retorno = newRetorno;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.FUNCAO__RETORNO, oldRetorno, retorno));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OiArdubotPackage.FUNCAO__PARAMETRO:
        return basicSetParametro(null, msgs);
      case OiArdubotPackage.FUNCAO__CODIGO:
        return ((InternalEList<?>)getCodigo()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OiArdubotPackage.FUNCAO__NAME:
        return getName();
      case OiArdubotPackage.FUNCAO__PARAMETRO:
        return getParametro();
      case OiArdubotPackage.FUNCAO__TIPO:
        return getTipo();
      case OiArdubotPackage.FUNCAO__CODIGO:
        return getCodigo();
      case OiArdubotPackage.FUNCAO__RETORNO:
        return getRetorno();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OiArdubotPackage.FUNCAO__NAME:
        setName((String)newValue);
        return;
      case OiArdubotPackage.FUNCAO__PARAMETRO:
        setParametro((Parametro)newValue);
        return;
      case OiArdubotPackage.FUNCAO__TIPO:
        setTipo((Tipo)newValue);
        return;
      case OiArdubotPackage.FUNCAO__CODIGO:
        getCodigo().clear();
        getCodigo().addAll((Collection<? extends Implementacao>)newValue);
        return;
      case OiArdubotPackage.FUNCAO__RETORNO:
        setRetorno((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OiArdubotPackage.FUNCAO__NAME:
        setName(NAME_EDEFAULT);
        return;
      case OiArdubotPackage.FUNCAO__PARAMETRO:
        setParametro((Parametro)null);
        return;
      case OiArdubotPackage.FUNCAO__TIPO:
        setTipo(TIPO_EDEFAULT);
        return;
      case OiArdubotPackage.FUNCAO__CODIGO:
        getCodigo().clear();
        return;
      case OiArdubotPackage.FUNCAO__RETORNO:
        setRetorno(RETORNO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OiArdubotPackage.FUNCAO__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case OiArdubotPackage.FUNCAO__PARAMETRO:
        return parametro != null;
      case OiArdubotPackage.FUNCAO__TIPO:
        return tipo != TIPO_EDEFAULT;
      case OiArdubotPackage.FUNCAO__CODIGO:
        return codigo != null && !codigo.isEmpty();
      case OiArdubotPackage.FUNCAO__RETORNO:
        return RETORNO_EDEFAULT == null ? retorno != null : !RETORNO_EDEFAULT.equals(retorno);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", tipo: ");
    result.append(tipo);
    result.append(", retorno: ");
    result.append(retorno);
    result.append(')');
    return result.toString();
  }

} //FuncaoImpl
