/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot.impl;

import br.edu.utfpr.oiardubot.oiArdubot.FuncaoLerDigital;
import br.edu.utfpr.oiardubot.oiArdubot.LerDigital;
import br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage;
import br.edu.utfpr.oiardubot.oiArdubot.ReceberValor;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ler Digital</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.LerDigitalImpl#getAtribuicao <em>Atribuicao</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.LerDigitalImpl#getLer <em>Ler</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LerDigitalImpl extends ImplementacaoImpl implements LerDigital
{
  /**
   * The cached value of the '{@link #getAtribuicao() <em>Atribuicao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtribuicao()
   * @generated
   * @ordered
   */
  protected ReceberValor atribuicao;

  /**
   * The cached value of the '{@link #getLer() <em>Ler</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLer()
   * @generated
   * @ordered
   */
  protected FuncaoLerDigital ler;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LerDigitalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OiArdubotPackage.Literals.LER_DIGITAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReceberValor getAtribuicao()
  {
    return atribuicao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtribuicao(ReceberValor newAtribuicao, NotificationChain msgs)
  {
    ReceberValor oldAtribuicao = atribuicao;
    atribuicao = newAtribuicao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OiArdubotPackage.LER_DIGITAL__ATRIBUICAO, oldAtribuicao, newAtribuicao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAtribuicao(ReceberValor newAtribuicao)
  {
    if (newAtribuicao != atribuicao)
    {
      NotificationChain msgs = null;
      if (atribuicao != null)
        msgs = ((InternalEObject)atribuicao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.LER_DIGITAL__ATRIBUICAO, null, msgs);
      if (newAtribuicao != null)
        msgs = ((InternalEObject)newAtribuicao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.LER_DIGITAL__ATRIBUICAO, null, msgs);
      msgs = basicSetAtribuicao(newAtribuicao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.LER_DIGITAL__ATRIBUICAO, newAtribuicao, newAtribuicao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FuncaoLerDigital getLer()
  {
    return ler;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLer(FuncaoLerDigital newLer, NotificationChain msgs)
  {
    FuncaoLerDigital oldLer = ler;
    ler = newLer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OiArdubotPackage.LER_DIGITAL__LER, oldLer, newLer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLer(FuncaoLerDigital newLer)
  {
    if (newLer != ler)
    {
      NotificationChain msgs = null;
      if (ler != null)
        msgs = ((InternalEObject)ler).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.LER_DIGITAL__LER, null, msgs);
      if (newLer != null)
        msgs = ((InternalEObject)newLer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.LER_DIGITAL__LER, null, msgs);
      msgs = basicSetLer(newLer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.LER_DIGITAL__LER, newLer, newLer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OiArdubotPackage.LER_DIGITAL__ATRIBUICAO:
        return basicSetAtribuicao(null, msgs);
      case OiArdubotPackage.LER_DIGITAL__LER:
        return basicSetLer(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OiArdubotPackage.LER_DIGITAL__ATRIBUICAO:
        return getAtribuicao();
      case OiArdubotPackage.LER_DIGITAL__LER:
        return getLer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OiArdubotPackage.LER_DIGITAL__ATRIBUICAO:
        setAtribuicao((ReceberValor)newValue);
        return;
      case OiArdubotPackage.LER_DIGITAL__LER:
        setLer((FuncaoLerDigital)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OiArdubotPackage.LER_DIGITAL__ATRIBUICAO:
        setAtribuicao((ReceberValor)null);
        return;
      case OiArdubotPackage.LER_DIGITAL__LER:
        setLer((FuncaoLerDigital)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OiArdubotPackage.LER_DIGITAL__ATRIBUICAO:
        return atribuicao != null;
      case OiArdubotPackage.LER_DIGITAL__LER:
        return ler != null;
    }
    return super.eIsSet(featureID);
  }

} //LerDigitalImpl
