/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot.impl;

import br.edu.utfpr.oiardubot.oiArdubot.NovaVariavelRecebe;
import br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Nova Variavel Recebe</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NovaVariavelRecebeImpl extends MinimalEObjectImpl.Container implements NovaVariavelRecebe
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NovaVariavelRecebeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OiArdubotPackage.Literals.NOVA_VARIAVEL_RECEBE;
  }

} //NovaVariavelRecebeImpl
