/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot.impl;

import br.edu.utfpr.oiardubot.oiArdubot.Andar;
import br.edu.utfpr.oiardubot.oiArdubot.Bip;
import br.edu.utfpr.oiardubot.oiArdubot.Caso;
import br.edu.utfpr.oiardubot.oiArdubot.Codigo;
import br.edu.utfpr.oiardubot.oiArdubot.Constante;
import br.edu.utfpr.oiardubot.oiArdubot.ConstanteVariavel;
import br.edu.utfpr.oiardubot.oiArdubot.ConteudoEscrever;
import br.edu.utfpr.oiardubot.oiArdubot.Controle;
import br.edu.utfpr.oiardubot.oiArdubot.Desligar;
import br.edu.utfpr.oiardubot.oiArdubot.Direcao;
import br.edu.utfpr.oiardubot.oiArdubot.Enquanto;
import br.edu.utfpr.oiardubot.oiArdubot.Escolha;
import br.edu.utfpr.oiardubot.oiArdubot.Escrever;
import br.edu.utfpr.oiardubot.oiArdubot.Espera;
import br.edu.utfpr.oiardubot.oiArdubot.ExistenteVariavelRecebe;
import br.edu.utfpr.oiardubot.oiArdubot.FimPara;
import br.edu.utfpr.oiardubot.oiArdubot.Fimse;
import br.edu.utfpr.oiardubot.oiArdubot.Funcao;
import br.edu.utfpr.oiardubot.oiArdubot.FuncaoLerAnalogica;
import br.edu.utfpr.oiardubot.oiArdubot.FuncaoLerDigital;
import br.edu.utfpr.oiardubot.oiArdubot.Implementacao;
import br.edu.utfpr.oiardubot.oiArdubot.Inteiro;
import br.edu.utfpr.oiardubot.oiArdubot.Ler;
import br.edu.utfpr.oiardubot.oiArdubot.LerAnalogica;
import br.edu.utfpr.oiardubot.oiArdubot.LerDigital;
import br.edu.utfpr.oiardubot.oiArdubot.Ligar;
import br.edu.utfpr.oiardubot.oiArdubot.Logico;
import br.edu.utfpr.oiardubot.oiArdubot.Model;
import br.edu.utfpr.oiardubot.oiArdubot.MotorDC;
import br.edu.utfpr.oiardubot.oiArdubot.Nome;
import br.edu.utfpr.oiardubot.oiArdubot.NovaVariavelRecebe;
import br.edu.utfpr.oiardubot.oiArdubot.OiArdubotFactory;
import br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage;
import br.edu.utfpr.oiardubot.oiArdubot.Para;
import br.edu.utfpr.oiardubot.oiArdubot.Parametro;
import br.edu.utfpr.oiardubot.oiArdubot.Parar;
import br.edu.utfpr.oiardubot.oiArdubot.Porta;
import br.edu.utfpr.oiardubot.oiArdubot.PortaAnalogica;
import br.edu.utfpr.oiardubot.oiArdubot.PortaDigital;
import br.edu.utfpr.oiardubot.oiArdubot.ReceberValor;
import br.edu.utfpr.oiardubot.oiArdubot.Repita;
import br.edu.utfpr.oiardubot.oiArdubot.Se;
import br.edu.utfpr.oiardubot.oiArdubot.Senao;
import br.edu.utfpr.oiardubot.oiArdubot.Servo;
import br.edu.utfpr.oiardubot.oiArdubot.Soma;
import br.edu.utfpr.oiardubot.oiArdubot.Tela;
import br.edu.utfpr.oiardubot.oiArdubot.Texto;
import br.edu.utfpr.oiardubot.oiArdubot.Tipo;
import br.edu.utfpr.oiardubot.oiArdubot.TipoPorta;
import br.edu.utfpr.oiardubot.oiArdubot.Variavel;
import br.edu.utfpr.oiardubot.oiArdubot.VariavelExistente;
import br.edu.utfpr.oiardubot.oiArdubot.VariavelNome;
import br.edu.utfpr.oiardubot.oiArdubot.VariavelOuPorta;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class OiArdubotPackageImpl extends EPackageImpl implements OiArdubotPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass codigoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass implementacaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass portaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass portaAnalogicaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass portaDigitalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass receberValorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existenteVariavelRecebeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass novaVariavelRecebeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variavelNomeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variavelOuPortaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nomeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass conteudoEscreverEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass textoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass inteiroEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variavelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variavelExistenteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constanteVariavelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constanteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass controleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass logicoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lerDigitalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass funcaoLerDigitalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lerAnalogicaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass funcaoLerAnalogicaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass escreverEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass telaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass bipEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ligarEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass desligarEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass servoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass motorDCEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass andarEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pararEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass paraEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fimParaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enquantoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass repitaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass seEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fimseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass senaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass escolhaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass casoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass funcaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass parametroEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass esperaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass somaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum tipoPortaEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum tipoEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum direcaoEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private OiArdubotPackageImpl()
  {
    super(eNS_URI, OiArdubotFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link OiArdubotPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static OiArdubotPackage init()
  {
    if (isInited) return (OiArdubotPackage)EPackage.Registry.INSTANCE.getEPackage(OiArdubotPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredOiArdubotPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    OiArdubotPackageImpl theOiArdubotPackage = registeredOiArdubotPackage instanceof OiArdubotPackageImpl ? (OiArdubotPackageImpl)registeredOiArdubotPackage : new OiArdubotPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theOiArdubotPackage.createPackageContents();

    // Initialize created meta-data
    theOiArdubotPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theOiArdubotPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(OiArdubotPackage.eNS_URI, theOiArdubotPackage);
    return theOiArdubotPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModel_Var()
  {
    return (EAttribute)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Variaveis()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Constantes()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModel_Ini()
  {
    return (EAttribute)modelEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Codigo()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModel_Fim()
  {
    return (EAttribute)modelEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCodigo()
  {
    return codigoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCodigo_Code()
  {
    return (EReference)codigoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImplementacao()
  {
    return implementacaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPorta()
  {
    return portaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPorta_Name()
  {
    return (EReference)portaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPortaAnalogica()
  {
    return portaAnalogicaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPortaAnalogica_Valor()
  {
    return (EAttribute)portaAnalogicaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPortaDigital()
  {
    return portaDigitalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPortaDigital_Valor()
  {
    return (EAttribute)portaDigitalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getReceberValor()
  {
    return receberValorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getReceberValor_Tipo()
  {
    return (EReference)receberValorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistenteVariavelRecebe()
  {
    return existenteVariavelRecebeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExistenteVariavelRecebe_Name()
  {
    return (EAttribute)existenteVariavelRecebeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNovaVariavelRecebe()
  {
    return novaVariavelRecebeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVariavelNome()
  {
    return variavelNomeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVariavelNome_Tipo()
  {
    return (EAttribute)variavelNomeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVariavelNome_Name()
  {
    return (EAttribute)variavelNomeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVariavelOuPorta()
  {
    return variavelOuPortaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVariavelOuPorta_Name()
  {
    return (EReference)variavelOuPortaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNome()
  {
    return nomeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNome_Name()
  {
    return (EAttribute)nomeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConteudoEscrever()
  {
    return conteudoEscreverEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTexto()
  {
    return textoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTexto_Name()
  {
    return (EAttribute)textoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInteiro()
  {
    return inteiroEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInteiro_Name()
  {
    return (EAttribute)inteiroEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVariavel()
  {
    return variavelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVariavel_VariavelNome()
  {
    return (EReference)variavelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVariavel_Valor()
  {
    return (EAttribute)variavelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVariavelExistente()
  {
    return variavelExistenteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVariavelExistente_Atribuicao()
  {
    return (EReference)variavelExistenteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVariavelExistente_Valor()
  {
    return (EAttribute)variavelExistenteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConstanteVariavel()
  {
    return constanteVariavelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstanteVariavel_Tipo()
  {
    return (EAttribute)constanteVariavelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstanteVariavel_VariavelNome()
  {
    return (EAttribute)constanteVariavelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstanteVariavel_Valor()
  {
    return (EAttribute)constanteVariavelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConstante()
  {
    return constanteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConstante_Variavel()
  {
    return (EReference)constanteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getControle()
  {
    return controleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getControle_Paras()
  {
    return (EReference)controleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLogico()
  {
    return logicoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLogico_Relation()
  {
    return (EAttribute)logicoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLer()
  {
    return lerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLer_Atribuicao()
  {
    return (EReference)lerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLer_Ler()
  {
    return (EAttribute)lerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLerDigital()
  {
    return lerDigitalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLerDigital_Atribuicao()
  {
    return (EReference)lerDigitalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLerDigital_Ler()
  {
    return (EReference)lerDigitalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuncaoLerDigital()
  {
    return funcaoLerDigitalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFuncaoLerDigital_Porta()
  {
    return (EReference)funcaoLerDigitalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLerAnalogica()
  {
    return lerAnalogicaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLerAnalogica_Atribuicao()
  {
    return (EReference)lerAnalogicaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLerAnalogica_Ler()
  {
    return (EReference)lerAnalogicaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuncaoLerAnalogica()
  {
    return funcaoLerAnalogicaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFuncaoLerAnalogica_Porta()
  {
    return (EReference)funcaoLerAnalogicaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEscrever()
  {
    return escreverEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEscrever_Mensagem()
  {
    return (EReference)escreverEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTela()
  {
    return telaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTela_Mensagem()
  {
    return (EAttribute)telaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBip()
  {
    return bipEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBip_Tipo()
  {
    return (EAttribute)bipEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLigar()
  {
    return ligarEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLigar_TipoPorta()
  {
    return (EAttribute)ligarEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLigar_Porta()
  {
    return (EReference)ligarEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDesligar()
  {
    return desligarEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDesligar_TipoPorta()
  {
    return (EAttribute)desligarEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDesligar_Porta()
  {
    return (EReference)desligarEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getServo()
  {
    return servoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getServo_Porta()
  {
    return (EReference)servoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getServo_Posicao()
  {
    return (EAttribute)servoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMotorDC()
  {
    return motorDCEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMotorDC_Estado()
  {
    return (EAttribute)motorDCEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMotorDC_Direcao()
  {
    return (EAttribute)motorDCEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAndar()
  {
    return andarEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAndar_Porta()
  {
    return (EReference)andarEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAndar_Velocidade()
  {
    return (EAttribute)andarEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAndar_Direcao()
  {
    return (EAttribute)andarEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParar()
  {
    return pararEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParar_Porta()
  {
    return (EReference)pararEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPara()
  {
    return paraEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPara_Variavel()
  {
    return (EAttribute)paraEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPara_De()
  {
    return (EAttribute)paraEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPara_Ate()
  {
    return (EAttribute)paraEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPara_Code()
  {
    return (EReference)paraEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPara_Fimpara()
  {
    return (EReference)paraEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFimPara()
  {
    return fimParaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFimPara_Name()
  {
    return (EAttribute)fimParaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEnquanto()
  {
    return enquantoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnquanto_ValorEsquerda()
  {
    return (EAttribute)enquantoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEnquanto_Relacao()
  {
    return (EReference)enquantoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnquanto_ValorDireita()
  {
    return (EAttribute)enquantoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEnquanto_Code()
  {
    return (EReference)enquantoEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRepita()
  {
    return repitaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepita_Code()
  {
    return (EReference)repitaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepita_ValorEsquerda()
  {
    return (EAttribute)repitaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepita_Relacao()
  {
    return (EReference)repitaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepita_ValorDireita()
  {
    return (EAttribute)repitaEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSe()
  {
    return seEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSe_ValorEsquerda()
  {
    return (EAttribute)seEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSe_Relacao()
  {
    return (EReference)seEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSe_ValorDireita()
  {
    return (EAttribute)seEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSe_Code()
  {
    return (EReference)seEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSe_Senao()
  {
    return (EReference)seEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSe_Fimse()
  {
    return (EReference)seEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFimse()
  {
    return fimseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFimse_Name()
  {
    return (EAttribute)fimseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSenao()
  {
    return senaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSenao_Code()
  {
    return (EReference)senaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEscolha()
  {
    return escolhaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEscolha_Valor()
  {
    return (EAttribute)escolhaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEscolha_Casos()
  {
    return (EReference)escolhaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCaso()
  {
    return casoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCaso_Valor()
  {
    return (EAttribute)casoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCaso_Codigo()
  {
    return (EReference)casoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuncao()
  {
    return funcaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFuncao_Name()
  {
    return (EAttribute)funcaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFuncao_Parametro()
  {
    return (EReference)funcaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFuncao_Tipo()
  {
    return (EAttribute)funcaoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFuncao_Codigo()
  {
    return (EReference)funcaoEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFuncao_Retorno()
  {
    return (EAttribute)funcaoEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParametro()
  {
    return parametroEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParametro_Valor()
  {
    return (EReference)parametroEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEspera()
  {
    return esperaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEspera_Valor()
  {
    return (EAttribute)esperaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSoma()
  {
    return somaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSoma_Name()
  {
    return (EReference)somaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSoma_ValorEsquerda()
  {
    return (EAttribute)somaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSoma_ValorDireita()
  {
    return (EAttribute)somaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getTipoPorta()
  {
    return tipoPortaEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getTipo()
  {
    return tipoEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getDirecao()
  {
    return direcaoEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OiArdubotFactory getOiArdubotFactory()
  {
    return (OiArdubotFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEAttribute(modelEClass, MODEL__VAR);
    createEReference(modelEClass, MODEL__VARIAVEIS);
    createEReference(modelEClass, MODEL__CONSTANTES);
    createEAttribute(modelEClass, MODEL__INI);
    createEReference(modelEClass, MODEL__CODIGO);
    createEAttribute(modelEClass, MODEL__FIM);

    codigoEClass = createEClass(CODIGO);
    createEReference(codigoEClass, CODIGO__CODE);

    implementacaoEClass = createEClass(IMPLEMENTACAO);

    portaEClass = createEClass(PORTA);
    createEReference(portaEClass, PORTA__NAME);

    portaAnalogicaEClass = createEClass(PORTA_ANALOGICA);
    createEAttribute(portaAnalogicaEClass, PORTA_ANALOGICA__VALOR);

    portaDigitalEClass = createEClass(PORTA_DIGITAL);
    createEAttribute(portaDigitalEClass, PORTA_DIGITAL__VALOR);

    receberValorEClass = createEClass(RECEBER_VALOR);
    createEReference(receberValorEClass, RECEBER_VALOR__TIPO);

    existenteVariavelRecebeEClass = createEClass(EXISTENTE_VARIAVEL_RECEBE);
    createEAttribute(existenteVariavelRecebeEClass, EXISTENTE_VARIAVEL_RECEBE__NAME);

    novaVariavelRecebeEClass = createEClass(NOVA_VARIAVEL_RECEBE);

    variavelNomeEClass = createEClass(VARIAVEL_NOME);
    createEAttribute(variavelNomeEClass, VARIAVEL_NOME__TIPO);
    createEAttribute(variavelNomeEClass, VARIAVEL_NOME__NAME);

    variavelOuPortaEClass = createEClass(VARIAVEL_OU_PORTA);
    createEReference(variavelOuPortaEClass, VARIAVEL_OU_PORTA__NAME);

    nomeEClass = createEClass(NOME);
    createEAttribute(nomeEClass, NOME__NAME);

    conteudoEscreverEClass = createEClass(CONTEUDO_ESCREVER);

    textoEClass = createEClass(TEXTO);
    createEAttribute(textoEClass, TEXTO__NAME);

    inteiroEClass = createEClass(INTEIRO);
    createEAttribute(inteiroEClass, INTEIRO__NAME);

    variavelEClass = createEClass(VARIAVEL);
    createEReference(variavelEClass, VARIAVEL__VARIAVEL_NOME);
    createEAttribute(variavelEClass, VARIAVEL__VALOR);

    variavelExistenteEClass = createEClass(VARIAVEL_EXISTENTE);
    createEReference(variavelExistenteEClass, VARIAVEL_EXISTENTE__ATRIBUICAO);
    createEAttribute(variavelExistenteEClass, VARIAVEL_EXISTENTE__VALOR);

    constanteVariavelEClass = createEClass(CONSTANTE_VARIAVEL);
    createEAttribute(constanteVariavelEClass, CONSTANTE_VARIAVEL__TIPO);
    createEAttribute(constanteVariavelEClass, CONSTANTE_VARIAVEL__VARIAVEL_NOME);
    createEAttribute(constanteVariavelEClass, CONSTANTE_VARIAVEL__VALOR);

    constanteEClass = createEClass(CONSTANTE);
    createEReference(constanteEClass, CONSTANTE__VARIAVEL);

    controleEClass = createEClass(CONTROLE);
    createEReference(controleEClass, CONTROLE__PARAS);

    logicoEClass = createEClass(LOGICO);
    createEAttribute(logicoEClass, LOGICO__RELATION);

    lerEClass = createEClass(LER);
    createEReference(lerEClass, LER__ATRIBUICAO);
    createEAttribute(lerEClass, LER__LER);

    lerDigitalEClass = createEClass(LER_DIGITAL);
    createEReference(lerDigitalEClass, LER_DIGITAL__ATRIBUICAO);
    createEReference(lerDigitalEClass, LER_DIGITAL__LER);

    funcaoLerDigitalEClass = createEClass(FUNCAO_LER_DIGITAL);
    createEReference(funcaoLerDigitalEClass, FUNCAO_LER_DIGITAL__PORTA);

    lerAnalogicaEClass = createEClass(LER_ANALOGICA);
    createEReference(lerAnalogicaEClass, LER_ANALOGICA__ATRIBUICAO);
    createEReference(lerAnalogicaEClass, LER_ANALOGICA__LER);

    funcaoLerAnalogicaEClass = createEClass(FUNCAO_LER_ANALOGICA);
    createEReference(funcaoLerAnalogicaEClass, FUNCAO_LER_ANALOGICA__PORTA);

    escreverEClass = createEClass(ESCREVER);
    createEReference(escreverEClass, ESCREVER__MENSAGEM);

    telaEClass = createEClass(TELA);
    createEAttribute(telaEClass, TELA__MENSAGEM);

    bipEClass = createEClass(BIP);
    createEAttribute(bipEClass, BIP__TIPO);

    ligarEClass = createEClass(LIGAR);
    createEAttribute(ligarEClass, LIGAR__TIPO_PORTA);
    createEReference(ligarEClass, LIGAR__PORTA);

    desligarEClass = createEClass(DESLIGAR);
    createEAttribute(desligarEClass, DESLIGAR__TIPO_PORTA);
    createEReference(desligarEClass, DESLIGAR__PORTA);

    servoEClass = createEClass(SERVO);
    createEReference(servoEClass, SERVO__PORTA);
    createEAttribute(servoEClass, SERVO__POSICAO);

    motorDCEClass = createEClass(MOTOR_DC);
    createEAttribute(motorDCEClass, MOTOR_DC__ESTADO);
    createEAttribute(motorDCEClass, MOTOR_DC__DIRECAO);

    andarEClass = createEClass(ANDAR);
    createEReference(andarEClass, ANDAR__PORTA);
    createEAttribute(andarEClass, ANDAR__VELOCIDADE);
    createEAttribute(andarEClass, ANDAR__DIRECAO);

    pararEClass = createEClass(PARAR);
    createEReference(pararEClass, PARAR__PORTA);

    paraEClass = createEClass(PARA);
    createEAttribute(paraEClass, PARA__VARIAVEL);
    createEAttribute(paraEClass, PARA__DE);
    createEAttribute(paraEClass, PARA__ATE);
    createEReference(paraEClass, PARA__CODE);
    createEReference(paraEClass, PARA__FIMPARA);

    fimParaEClass = createEClass(FIM_PARA);
    createEAttribute(fimParaEClass, FIM_PARA__NAME);

    enquantoEClass = createEClass(ENQUANTO);
    createEAttribute(enquantoEClass, ENQUANTO__VALOR_ESQUERDA);
    createEReference(enquantoEClass, ENQUANTO__RELACAO);
    createEAttribute(enquantoEClass, ENQUANTO__VALOR_DIREITA);
    createEReference(enquantoEClass, ENQUANTO__CODE);

    repitaEClass = createEClass(REPITA);
    createEReference(repitaEClass, REPITA__CODE);
    createEAttribute(repitaEClass, REPITA__VALOR_ESQUERDA);
    createEReference(repitaEClass, REPITA__RELACAO);
    createEAttribute(repitaEClass, REPITA__VALOR_DIREITA);

    seEClass = createEClass(SE);
    createEAttribute(seEClass, SE__VALOR_ESQUERDA);
    createEReference(seEClass, SE__RELACAO);
    createEAttribute(seEClass, SE__VALOR_DIREITA);
    createEReference(seEClass, SE__CODE);
    createEReference(seEClass, SE__SENAO);
    createEReference(seEClass, SE__FIMSE);

    fimseEClass = createEClass(FIMSE);
    createEAttribute(fimseEClass, FIMSE__NAME);

    senaoEClass = createEClass(SENAO);
    createEReference(senaoEClass, SENAO__CODE);

    escolhaEClass = createEClass(ESCOLHA);
    createEAttribute(escolhaEClass, ESCOLHA__VALOR);
    createEReference(escolhaEClass, ESCOLHA__CASOS);

    casoEClass = createEClass(CASO);
    createEAttribute(casoEClass, CASO__VALOR);
    createEReference(casoEClass, CASO__CODIGO);

    funcaoEClass = createEClass(FUNCAO);
    createEAttribute(funcaoEClass, FUNCAO__NAME);
    createEReference(funcaoEClass, FUNCAO__PARAMETRO);
    createEAttribute(funcaoEClass, FUNCAO__TIPO);
    createEReference(funcaoEClass, FUNCAO__CODIGO);
    createEAttribute(funcaoEClass, FUNCAO__RETORNO);

    parametroEClass = createEClass(PARAMETRO);
    createEReference(parametroEClass, PARAMETRO__VALOR);

    esperaEClass = createEClass(ESPERA);
    createEAttribute(esperaEClass, ESPERA__VALOR);

    somaEClass = createEClass(SOMA);
    createEReference(somaEClass, SOMA__NAME);
    createEAttribute(somaEClass, SOMA__VALOR_ESQUERDA);
    createEAttribute(somaEClass, SOMA__VALOR_DIREITA);

    // Create enums
    tipoPortaEEnum = createEEnum(TIPO_PORTA);
    tipoEEnum = createEEnum(TIPO);
    direcaoEEnum = createEEnum(DIRECAO);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    variavelNomeEClass.getESuperTypes().add(this.getNovaVariavelRecebe());
    nomeEClass.getESuperTypes().add(this.getConteudoEscrever());
    textoEClass.getESuperTypes().add(this.getConteudoEscrever());
    inteiroEClass.getESuperTypes().add(this.getConteudoEscrever());
    variavelExistenteEClass.getESuperTypes().add(this.getImplementacao());
    lerEClass.getESuperTypes().add(this.getImplementacao());
    lerDigitalEClass.getESuperTypes().add(this.getImplementacao());
    lerAnalogicaEClass.getESuperTypes().add(this.getImplementacao());
    escreverEClass.getESuperTypes().add(this.getImplementacao());
    telaEClass.getESuperTypes().add(this.getImplementacao());
    bipEClass.getESuperTypes().add(this.getImplementacao());
    ligarEClass.getESuperTypes().add(this.getImplementacao());
    desligarEClass.getESuperTypes().add(this.getImplementacao());
    servoEClass.getESuperTypes().add(this.getImplementacao());
    motorDCEClass.getESuperTypes().add(this.getImplementacao());
    andarEClass.getESuperTypes().add(this.getImplementacao());
    pararEClass.getESuperTypes().add(this.getImplementacao());
    paraEClass.getESuperTypes().add(this.getImplementacao());
    enquantoEClass.getESuperTypes().add(this.getImplementacao());
    repitaEClass.getESuperTypes().add(this.getImplementacao());
    seEClass.getESuperTypes().add(this.getImplementacao());
    escolhaEClass.getESuperTypes().add(this.getImplementacao());
    funcaoEClass.getESuperTypes().add(this.getImplementacao());
    esperaEClass.getESuperTypes().add(this.getImplementacao());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModel_Var(), ecorePackage.getEString(), "var", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Variaveis(), this.getVariavel(), null, "variaveis", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Constantes(), this.getConstante(), null, "constantes", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getModel_Ini(), ecorePackage.getEString(), "ini", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Codigo(), this.getImplementacao(), null, "codigo", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getModel_Fim(), ecorePackage.getEString(), "fim", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(codigoEClass, Codigo.class, "Codigo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCodigo_Code(), this.getImplementacao(), null, "code", null, 0, -1, Codigo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(implementacaoEClass, Implementacao.class, "Implementacao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(portaEClass, Porta.class, "Porta", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPorta_Name(), ecorePackage.getEObject(), null, "name", null, 0, 1, Porta.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(portaAnalogicaEClass, PortaAnalogica.class, "PortaAnalogica", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPortaAnalogica_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, PortaAnalogica.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(portaDigitalEClass, PortaDigital.class, "PortaDigital", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPortaDigital_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, PortaDigital.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(receberValorEClass, ReceberValor.class, "ReceberValor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getReceberValor_Tipo(), ecorePackage.getEObject(), null, "tipo", null, 0, 1, ReceberValor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existenteVariavelRecebeEClass, ExistenteVariavelRecebe.class, "ExistenteVariavelRecebe", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExistenteVariavelRecebe_Name(), ecorePackage.getEString(), "name", null, 0, 1, ExistenteVariavelRecebe.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(novaVariavelRecebeEClass, NovaVariavelRecebe.class, "NovaVariavelRecebe", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(variavelNomeEClass, VariavelNome.class, "VariavelNome", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVariavelNome_Tipo(), this.getTipo(), "tipo", null, 0, 1, VariavelNome.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVariavelNome_Name(), ecorePackage.getEString(), "name", null, 0, 1, VariavelNome.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variavelOuPortaEClass, VariavelOuPorta.class, "VariavelOuPorta", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getVariavelOuPorta_Name(), this.getPorta(), null, "name", null, 0, 1, VariavelOuPorta.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(nomeEClass, Nome.class, "Nome", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNome_Name(), ecorePackage.getEString(), "name", null, 0, 1, Nome.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(conteudoEscreverEClass, ConteudoEscrever.class, "ConteudoEscrever", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(textoEClass, Texto.class, "Texto", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTexto_Name(), ecorePackage.getEString(), "name", null, 0, 1, Texto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(inteiroEClass, Inteiro.class, "Inteiro", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInteiro_Name(), ecorePackage.getEInt(), "name", null, 0, 1, Inteiro.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variavelEClass, Variavel.class, "Variavel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getVariavel_VariavelNome(), this.getVariavelNome(), null, "variavelNome", null, 0, 1, Variavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVariavel_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, Variavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variavelExistenteEClass, VariavelExistente.class, "VariavelExistente", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getVariavelExistente_Atribuicao(), this.getExistenteVariavelRecebe(), null, "atribuicao", null, 0, 1, VariavelExistente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVariavelExistente_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, VariavelExistente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constanteVariavelEClass, ConstanteVariavel.class, "ConstanteVariavel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstanteVariavel_Tipo(), this.getTipo(), "tipo", null, 0, 1, ConstanteVariavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConstanteVariavel_VariavelNome(), ecorePackage.getEString(), "variavelNome", null, 0, 1, ConstanteVariavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConstanteVariavel_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, ConstanteVariavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constanteEClass, Constante.class, "Constante", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getConstante_Variavel(), this.getConstanteVariavel(), null, "variavel", null, 0, 1, Constante.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(controleEClass, Controle.class, "Controle", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getControle_Paras(), this.getPara(), null, "paras", null, 0, -1, Controle.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(logicoEClass, Logico.class, "Logico", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLogico_Relation(), ecorePackage.getEString(), "relation", null, 0, 1, Logico.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lerEClass, Ler.class, "Ler", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLer_Atribuicao(), this.getReceberValor(), null, "atribuicao", null, 0, 1, Ler.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLer_Ler(), ecorePackage.getEString(), "ler", null, 0, 1, Ler.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lerDigitalEClass, LerDigital.class, "LerDigital", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLerDigital_Atribuicao(), this.getReceberValor(), null, "atribuicao", null, 0, 1, LerDigital.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLerDigital_Ler(), this.getFuncaoLerDigital(), null, "ler", null, 0, 1, LerDigital.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(funcaoLerDigitalEClass, FuncaoLerDigital.class, "FuncaoLerDigital", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFuncaoLerDigital_Porta(), this.getPorta(), null, "porta", null, 0, 1, FuncaoLerDigital.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lerAnalogicaEClass, LerAnalogica.class, "LerAnalogica", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLerAnalogica_Atribuicao(), this.getReceberValor(), null, "atribuicao", null, 0, 1, LerAnalogica.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLerAnalogica_Ler(), this.getFuncaoLerAnalogica(), null, "ler", null, 0, 1, LerAnalogica.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(funcaoLerAnalogicaEClass, FuncaoLerAnalogica.class, "FuncaoLerAnalogica", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFuncaoLerAnalogica_Porta(), this.getPorta(), null, "porta", null, 0, 1, FuncaoLerAnalogica.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(escreverEClass, Escrever.class, "Escrever", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEscrever_Mensagem(), this.getConteudoEscrever(), null, "mensagem", null, 0, 1, Escrever.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(telaEClass, Tela.class, "Tela", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTela_Mensagem(), ecorePackage.getEString(), "mensagem", null, 0, 1, Tela.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(bipEClass, Bip.class, "Bip", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBip_Tipo(), ecorePackage.getEString(), "tipo", null, 0, 1, Bip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ligarEClass, Ligar.class, "Ligar", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLigar_TipoPorta(), this.getTipoPorta(), "tipoPorta", null, 0, 1, Ligar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLigar_Porta(), this.getPorta(), null, "porta", null, 0, 1, Ligar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(desligarEClass, Desligar.class, "Desligar", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDesligar_TipoPorta(), this.getTipoPorta(), "tipoPorta", null, 0, 1, Desligar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDesligar_Porta(), this.getPorta(), null, "porta", null, 0, 1, Desligar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(servoEClass, Servo.class, "Servo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getServo_Porta(), this.getVariavelOuPorta(), null, "porta", null, 0, 1, Servo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getServo_Posicao(), ecorePackage.getEInt(), "posicao", null, 0, 1, Servo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(motorDCEClass, MotorDC.class, "MotorDC", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMotorDC_Estado(), ecorePackage.getEInt(), "estado", null, 0, 1, MotorDC.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMotorDC_Direcao(), this.getDirecao(), "direcao", null, 0, 1, MotorDC.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(andarEClass, Andar.class, "Andar", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAndar_Porta(), this.getVariavelOuPorta(), null, "porta", null, 0, 1, Andar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAndar_Velocidade(), ecorePackage.getEInt(), "velocidade", null, 0, 1, Andar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAndar_Direcao(), this.getDirecao(), "direcao", null, 0, 1, Andar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(pararEClass, Parar.class, "Parar", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParar_Porta(), this.getPorta(), null, "porta", null, 0, 1, Parar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(paraEClass, Para.class, "Para", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPara_Variavel(), ecorePackage.getEString(), "variavel", null, 0, 1, Para.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPara_De(), ecorePackage.getEInt(), "de", null, 0, 1, Para.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPara_Ate(), ecorePackage.getEInt(), "ate", null, 0, 1, Para.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPara_Code(), this.getImplementacao(), null, "code", null, 0, -1, Para.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPara_Fimpara(), this.getFimPara(), null, "fimpara", null, 0, 1, Para.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fimParaEClass, FimPara.class, "FimPara", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFimPara_Name(), ecorePackage.getEString(), "name", null, 0, 1, FimPara.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enquantoEClass, Enquanto.class, "Enquanto", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEnquanto_ValorEsquerda(), ecorePackage.getEString(), "valorEsquerda", null, 0, 1, Enquanto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEnquanto_Relacao(), this.getLogico(), null, "relacao", null, 0, 1, Enquanto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnquanto_ValorDireita(), ecorePackage.getEString(), "valorDireita", null, 0, 1, Enquanto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEnquanto_Code(), this.getImplementacao(), null, "code", null, 0, -1, Enquanto.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(repitaEClass, Repita.class, "Repita", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRepita_Code(), this.getImplementacao(), null, "code", null, 0, -1, Repita.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRepita_ValorEsquerda(), ecorePackage.getEString(), "valorEsquerda", null, 0, 1, Repita.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRepita_Relacao(), this.getLogico(), null, "relacao", null, 0, 1, Repita.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRepita_ValorDireita(), ecorePackage.getEString(), "valorDireita", null, 0, 1, Repita.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(seEClass, Se.class, "Se", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSe_ValorEsquerda(), ecorePackage.getEString(), "valorEsquerda", null, 0, 1, Se.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSe_Relacao(), this.getLogico(), null, "relacao", null, 0, 1, Se.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSe_ValorDireita(), ecorePackage.getEString(), "valorDireita", null, 0, 1, Se.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSe_Code(), this.getImplementacao(), null, "code", null, 0, -1, Se.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSe_Senao(), this.getSenao(), null, "senao", null, 0, 1, Se.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSe_Fimse(), this.getFimse(), null, "fimse", null, 0, 1, Se.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fimseEClass, Fimse.class, "Fimse", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFimse_Name(), ecorePackage.getEString(), "name", null, 0, 1, Fimse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(senaoEClass, Senao.class, "Senao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSenao_Code(), this.getImplementacao(), null, "code", null, 0, -1, Senao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(escolhaEClass, Escolha.class, "Escolha", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEscolha_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, Escolha.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEscolha_Casos(), this.getCaso(), null, "casos", null, 0, -1, Escolha.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(casoEClass, Caso.class, "Caso", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCaso_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, Caso.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCaso_Codigo(), this.getCodigo(), null, "codigo", null, 0, -1, Caso.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(funcaoEClass, Funcao.class, "Funcao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFuncao_Name(), ecorePackage.getEString(), "name", null, 0, 1, Funcao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFuncao_Parametro(), this.getParametro(), null, "parametro", null, 0, 1, Funcao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFuncao_Tipo(), this.getTipo(), "tipo", null, 0, 1, Funcao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFuncao_Codigo(), this.getImplementacao(), null, "codigo", null, 0, -1, Funcao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFuncao_Retorno(), ecorePackage.getEString(), "retorno", null, 0, 1, Funcao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(parametroEClass, Parametro.class, "Parametro", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParametro_Valor(), this.getVariavelNome(), null, "valor", null, 0, -1, Parametro.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(esperaEClass, Espera.class, "Espera", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEspera_Valor(), ecorePackage.getEInt(), "valor", null, 0, 1, Espera.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(somaEClass, Soma.class, "Soma", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSoma_Name(), this.getReceberValor(), null, "name", null, 0, 1, Soma.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSoma_ValorEsquerda(), ecorePackage.getEString(), "valorEsquerda", null, 0, 1, Soma.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSoma_ValorDireita(), ecorePackage.getEString(), "valorDireita", null, 0, 1, Soma.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(tipoPortaEEnum, TipoPorta.class, "TipoPorta");
    addEEnumLiteral(tipoPortaEEnum, TipoPorta.DIGITAL);
    addEEnumLiteral(tipoPortaEEnum, TipoPorta.ANALOGICA);

    initEEnum(tipoEEnum, Tipo.class, "Tipo");
    addEEnumLiteral(tipoEEnum, Tipo.TEXTO);
    addEEnumLiteral(tipoEEnum, Tipo.NUMERO);

    initEEnum(direcaoEEnum, Direcao.class, "Direcao");
    addEEnumLiteral(direcaoEEnum, Direcao.FRENTE);
    addEEnumLiteral(direcaoEEnum, Direcao.TRAS);

    // Create resource
    createResource(eNS_URI);
  }

} //OiArdubotPackageImpl
