/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot.impl;

import br.edu.utfpr.oiardubot.oiArdubot.Fimse;
import br.edu.utfpr.oiardubot.oiArdubot.Implementacao;
import br.edu.utfpr.oiardubot.oiArdubot.Logico;
import br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage;
import br.edu.utfpr.oiardubot.oiArdubot.Se;
import br.edu.utfpr.oiardubot.oiArdubot.Senao;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Se</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SeImpl#getValorEsquerda <em>Valor Esquerda</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SeImpl#getRelacao <em>Relacao</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SeImpl#getValorDireita <em>Valor Direita</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SeImpl#getCode <em>Code</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SeImpl#getSenao <em>Senao</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SeImpl#getFimse <em>Fimse</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SeImpl extends ImplementacaoImpl implements Se
{
  /**
   * The default value of the '{@link #getValorEsquerda() <em>Valor Esquerda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorEsquerda()
   * @generated
   * @ordered
   */
  protected static final String VALOR_ESQUERDA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValorEsquerda() <em>Valor Esquerda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorEsquerda()
   * @generated
   * @ordered
   */
  protected String valorEsquerda = VALOR_ESQUERDA_EDEFAULT;

  /**
   * The cached value of the '{@link #getRelacao() <em>Relacao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelacao()
   * @generated
   * @ordered
   */
  protected Logico relacao;

  /**
   * The default value of the '{@link #getValorDireita() <em>Valor Direita</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorDireita()
   * @generated
   * @ordered
   */
  protected static final String VALOR_DIREITA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValorDireita() <em>Valor Direita</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorDireita()
   * @generated
   * @ordered
   */
  protected String valorDireita = VALOR_DIREITA_EDEFAULT;

  /**
   * The cached value of the '{@link #getCode() <em>Code</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCode()
   * @generated
   * @ordered
   */
  protected EList<Implementacao> code;

  /**
   * The cached value of the '{@link #getSenao() <em>Senao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSenao()
   * @generated
   * @ordered
   */
  protected Senao senao;

  /**
   * The cached value of the '{@link #getFimse() <em>Fimse</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFimse()
   * @generated
   * @ordered
   */
  protected Fimse fimse;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OiArdubotPackage.Literals.SE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getValorEsquerda()
  {
    return valorEsquerda;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValorEsquerda(String newValorEsquerda)
  {
    String oldValorEsquerda = valorEsquerda;
    valorEsquerda = newValorEsquerda;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SE__VALOR_ESQUERDA, oldValorEsquerda, valorEsquerda));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Logico getRelacao()
  {
    return relacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRelacao(Logico newRelacao, NotificationChain msgs)
  {
    Logico oldRelacao = relacao;
    relacao = newRelacao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SE__RELACAO, oldRelacao, newRelacao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelacao(Logico newRelacao)
  {
    if (newRelacao != relacao)
    {
      NotificationChain msgs = null;
      if (relacao != null)
        msgs = ((InternalEObject)relacao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.SE__RELACAO, null, msgs);
      if (newRelacao != null)
        msgs = ((InternalEObject)newRelacao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.SE__RELACAO, null, msgs);
      msgs = basicSetRelacao(newRelacao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SE__RELACAO, newRelacao, newRelacao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getValorDireita()
  {
    return valorDireita;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValorDireita(String newValorDireita)
  {
    String oldValorDireita = valorDireita;
    valorDireita = newValorDireita;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SE__VALOR_DIREITA, oldValorDireita, valorDireita));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Implementacao> getCode()
  {
    if (code == null)
    {
      code = new EObjectContainmentEList<Implementacao>(Implementacao.class, this, OiArdubotPackage.SE__CODE);
    }
    return code;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Senao getSenao()
  {
    return senao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSenao(Senao newSenao, NotificationChain msgs)
  {
    Senao oldSenao = senao;
    senao = newSenao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SE__SENAO, oldSenao, newSenao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSenao(Senao newSenao)
  {
    if (newSenao != senao)
    {
      NotificationChain msgs = null;
      if (senao != null)
        msgs = ((InternalEObject)senao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.SE__SENAO, null, msgs);
      if (newSenao != null)
        msgs = ((InternalEObject)newSenao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.SE__SENAO, null, msgs);
      msgs = basicSetSenao(newSenao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SE__SENAO, newSenao, newSenao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fimse getFimse()
  {
    return fimse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFimse(Fimse newFimse, NotificationChain msgs)
  {
    Fimse oldFimse = fimse;
    fimse = newFimse;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SE__FIMSE, oldFimse, newFimse);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFimse(Fimse newFimse)
  {
    if (newFimse != fimse)
    {
      NotificationChain msgs = null;
      if (fimse != null)
        msgs = ((InternalEObject)fimse).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.SE__FIMSE, null, msgs);
      if (newFimse != null)
        msgs = ((InternalEObject)newFimse).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.SE__FIMSE, null, msgs);
      msgs = basicSetFimse(newFimse, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SE__FIMSE, newFimse, newFimse));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SE__RELACAO:
        return basicSetRelacao(null, msgs);
      case OiArdubotPackage.SE__CODE:
        return ((InternalEList<?>)getCode()).basicRemove(otherEnd, msgs);
      case OiArdubotPackage.SE__SENAO:
        return basicSetSenao(null, msgs);
      case OiArdubotPackage.SE__FIMSE:
        return basicSetFimse(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SE__VALOR_ESQUERDA:
        return getValorEsquerda();
      case OiArdubotPackage.SE__RELACAO:
        return getRelacao();
      case OiArdubotPackage.SE__VALOR_DIREITA:
        return getValorDireita();
      case OiArdubotPackage.SE__CODE:
        return getCode();
      case OiArdubotPackage.SE__SENAO:
        return getSenao();
      case OiArdubotPackage.SE__FIMSE:
        return getFimse();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SE__VALOR_ESQUERDA:
        setValorEsquerda((String)newValue);
        return;
      case OiArdubotPackage.SE__RELACAO:
        setRelacao((Logico)newValue);
        return;
      case OiArdubotPackage.SE__VALOR_DIREITA:
        setValorDireita((String)newValue);
        return;
      case OiArdubotPackage.SE__CODE:
        getCode().clear();
        getCode().addAll((Collection<? extends Implementacao>)newValue);
        return;
      case OiArdubotPackage.SE__SENAO:
        setSenao((Senao)newValue);
        return;
      case OiArdubotPackage.SE__FIMSE:
        setFimse((Fimse)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SE__VALOR_ESQUERDA:
        setValorEsquerda(VALOR_ESQUERDA_EDEFAULT);
        return;
      case OiArdubotPackage.SE__RELACAO:
        setRelacao((Logico)null);
        return;
      case OiArdubotPackage.SE__VALOR_DIREITA:
        setValorDireita(VALOR_DIREITA_EDEFAULT);
        return;
      case OiArdubotPackage.SE__CODE:
        getCode().clear();
        return;
      case OiArdubotPackage.SE__SENAO:
        setSenao((Senao)null);
        return;
      case OiArdubotPackage.SE__FIMSE:
        setFimse((Fimse)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SE__VALOR_ESQUERDA:
        return VALOR_ESQUERDA_EDEFAULT == null ? valorEsquerda != null : !VALOR_ESQUERDA_EDEFAULT.equals(valorEsquerda);
      case OiArdubotPackage.SE__RELACAO:
        return relacao != null;
      case OiArdubotPackage.SE__VALOR_DIREITA:
        return VALOR_DIREITA_EDEFAULT == null ? valorDireita != null : !VALOR_DIREITA_EDEFAULT.equals(valorDireita);
      case OiArdubotPackage.SE__CODE:
        return code != null && !code.isEmpty();
      case OiArdubotPackage.SE__SENAO:
        return senao != null;
      case OiArdubotPackage.SE__FIMSE:
        return fimse != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (valorEsquerda: ");
    result.append(valorEsquerda);
    result.append(", valorDireita: ");
    result.append(valorDireita);
    result.append(')');
    return result.toString();
  }

} //SeImpl
