/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.oiArdubot.impl;

import br.edu.utfpr.oiardubot.oiArdubot.OiArdubotPackage;
import br.edu.utfpr.oiardubot.oiArdubot.ReceberValor;
import br.edu.utfpr.oiardubot.oiArdubot.Soma;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Soma</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SomaImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SomaImpl#getValorEsquerda <em>Valor Esquerda</em>}</li>
 *   <li>{@link br.edu.utfpr.oiardubot.oiArdubot.impl.SomaImpl#getValorDireita <em>Valor Direita</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SomaImpl extends MinimalEObjectImpl.Container implements Soma
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected ReceberValor name;

  /**
   * The default value of the '{@link #getValorEsquerda() <em>Valor Esquerda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorEsquerda()
   * @generated
   * @ordered
   */
  protected static final String VALOR_ESQUERDA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValorEsquerda() <em>Valor Esquerda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorEsquerda()
   * @generated
   * @ordered
   */
  protected String valorEsquerda = VALOR_ESQUERDA_EDEFAULT;

  /**
   * The default value of the '{@link #getValorDireita() <em>Valor Direita</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorDireita()
   * @generated
   * @ordered
   */
  protected static final String VALOR_DIREITA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValorDireita() <em>Valor Direita</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValorDireita()
   * @generated
   * @ordered
   */
  protected String valorDireita = VALOR_DIREITA_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SomaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OiArdubotPackage.Literals.SOMA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReceberValor getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(ReceberValor newName, NotificationChain msgs)
  {
    ReceberValor oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SOMA__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(ReceberValor newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.SOMA__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OiArdubotPackage.SOMA__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SOMA__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getValorEsquerda()
  {
    return valorEsquerda;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValorEsquerda(String newValorEsquerda)
  {
    String oldValorEsquerda = valorEsquerda;
    valorEsquerda = newValorEsquerda;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SOMA__VALOR_ESQUERDA, oldValorEsquerda, valorEsquerda));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getValorDireita()
  {
    return valorDireita;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValorDireita(String newValorDireita)
  {
    String oldValorDireita = valorDireita;
    valorDireita = newValorDireita;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArdubotPackage.SOMA__VALOR_DIREITA, oldValorDireita, valorDireita));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SOMA__NAME:
        return basicSetName(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SOMA__NAME:
        return getName();
      case OiArdubotPackage.SOMA__VALOR_ESQUERDA:
        return getValorEsquerda();
      case OiArdubotPackage.SOMA__VALOR_DIREITA:
        return getValorDireita();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SOMA__NAME:
        setName((ReceberValor)newValue);
        return;
      case OiArdubotPackage.SOMA__VALOR_ESQUERDA:
        setValorEsquerda((String)newValue);
        return;
      case OiArdubotPackage.SOMA__VALOR_DIREITA:
        setValorDireita((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SOMA__NAME:
        setName((ReceberValor)null);
        return;
      case OiArdubotPackage.SOMA__VALOR_ESQUERDA:
        setValorEsquerda(VALOR_ESQUERDA_EDEFAULT);
        return;
      case OiArdubotPackage.SOMA__VALOR_DIREITA:
        setValorDireita(VALOR_DIREITA_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OiArdubotPackage.SOMA__NAME:
        return name != null;
      case OiArdubotPackage.SOMA__VALOR_ESQUERDA:
        return VALOR_ESQUERDA_EDEFAULT == null ? valorEsquerda != null : !VALOR_ESQUERDA_EDEFAULT.equals(valorEsquerda);
      case OiArdubotPackage.SOMA__VALOR_DIREITA:
        return VALOR_DIREITA_EDEFAULT == null ? valorDireita != null : !VALOR_DIREITA_EDEFAULT.equals(valorDireita);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (valorEsquerda: ");
    result.append(valorEsquerda);
    result.append(", valorDireita: ");
    result.append(valorDireita);
    result.append(')');
    return result.toString();
  }

} //SomaImpl
