/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.oiArduBot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Beep</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Beep#getTipo <em>Tipo</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getBeep()
 * @model
 * @generated
 */
public interface Beep extends EObject
{
  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * The literals are from the enumeration {@link br.edu.utfpr.fb.oiArduBot.TipoBeep}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see br.edu.utfpr.fb.oiArduBot.TipoBeep
   * @see #setTipo(TipoBeep)
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getBeep_Tipo()
   * @model
   * @generated
   */
  TipoBeep getTipo();

  /**
   * Sets the value of the '{@link br.edu.utfpr.fb.oiArduBot.Beep#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see br.edu.utfpr.fb.oiArduBot.TipoBeep
   * @see #getTipo()
   * @generated
   */
  void setTipo(TipoBeep value);

} // Beep
