/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.oiArduBot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Codigo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Codigo#getControles <em>Controles</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getCodigo()
 * @model
 * @generated
 */
public interface Codigo extends EObject
{
  /**
   * Returns the value of the '<em><b>Controles</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.fb.oiArduBot.Para}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controles</em>' containment reference list.
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getCodigo_Controles()
   * @model containment="true"
   * @generated
   */
  EList<Para> getControles();

} // Codigo
