/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.oiArduBot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Notificacao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Notificacao#getBeep <em>Beep</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getNotificacao()
 * @model
 * @generated
 */
public interface Notificacao extends EObject
{
  /**
   * Returns the value of the '<em><b>Beep</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.fb.oiArduBot.Beep}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beep</em>' containment reference list.
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getNotificacao_Beep()
   * @model containment="true"
   * @generated
   */
  EList<Beep> getBeep();

} // Notificacao
