/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.oiArduBot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Para</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Para#getDe <em>De</em>}</li>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Para#getAte <em>Ate</em>}</li>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Para#getPasso <em>Passo</em>}</li>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Para#getCodigoPara <em>Codigo Para</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getPara()
 * @model
 * @generated
 */
public interface Para extends EObject
{
  /**
   * Returns the value of the '<em><b>De</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>De</em>' attribute.
   * @see #setDe(int)
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getPara_De()
   * @model
   * @generated
   */
  int getDe();

  /**
   * Sets the value of the '{@link br.edu.utfpr.fb.oiArduBot.Para#getDe <em>De</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>De</em>' attribute.
   * @see #getDe()
   * @generated
   */
  void setDe(int value);

  /**
   * Returns the value of the '<em><b>Ate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ate</em>' attribute.
   * @see #setAte(int)
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getPara_Ate()
   * @model
   * @generated
   */
  int getAte();

  /**
   * Sets the value of the '{@link br.edu.utfpr.fb.oiArduBot.Para#getAte <em>Ate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ate</em>' attribute.
   * @see #getAte()
   * @generated
   */
  void setAte(int value);

  /**
   * Returns the value of the '<em><b>Passo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Passo</em>' attribute.
   * @see #setPasso(int)
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getPara_Passo()
   * @model
   * @generated
   */
  int getPasso();

  /**
   * Sets the value of the '{@link br.edu.utfpr.fb.oiArduBot.Para#getPasso <em>Passo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Passo</em>' attribute.
   * @see #getPasso()
   * @generated
   */
  void setPasso(int value);

  /**
   * Returns the value of the '<em><b>Codigo Para</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Codigo Para</em>' attribute.
   * @see #setCodigoPara(String)
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getPara_CodigoPara()
   * @model
   * @generated
   */
  String getCodigoPara();

  /**
   * Sets the value of the '{@link br.edu.utfpr.fb.oiArduBot.Para#getCodigoPara <em>Codigo Para</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Codigo Para</em>' attribute.
   * @see #getCodigoPara()
   * @generated
   */
  void setCodigoPara(String value);

} // Para
