/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.oiArduBot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Robo#getSensores <em>Sensores</em>}</li>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Robo#getAtuadores <em>Atuadores</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getRobo()
 * @model
 * @generated
 */
public interface Robo extends EObject
{
  /**
   * Returns the value of the '<em><b>Sensores</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.fb.oiArduBot.Sensoriamento}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensores</em>' containment reference list.
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getRobo_Sensores()
   * @model containment="true"
   * @generated
   */
  EList<Sensoriamento> getSensores();

  /**
   * Returns the value of the '<em><b>Atuadores</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.utfpr.fb.oiArduBot.Atuacao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atuadores</em>' containment reference list.
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getRobo_Atuadores()
   * @model containment="true"
   * @generated
   */
  EList<Atuacao> getAtuadores();

} // Robo
