/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.oiArduBot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensoriamento</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Sensoriamento#getSensor <em>Sensor</em>}</li>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Sensoriamento#getPorta <em>Porta</em>}</li>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.Sensoriamento#getTipo <em>Tipo</em>}</li>
 * </ul>
 *
 * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getSensoriamento()
 * @model
 * @generated
 */
public interface Sensoriamento extends EObject
{
  /**
   * Returns the value of the '<em><b>Sensor</b></em>' reference list.
   * The list contents are of type {@link br.edu.utfpr.fb.oiArduBot.Variavel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor</em>' reference list.
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getSensoriamento_Sensor()
   * @model
   * @generated
   */
  EList<Variavel> getSensor();

  /**
   * Returns the value of the '<em><b>Porta</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Porta</em>' attribute.
   * @see #setPorta(int)
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getSensoriamento_Porta()
   * @model
   * @generated
   */
  int getPorta();

  /**
   * Sets the value of the '{@link br.edu.utfpr.fb.oiArduBot.Sensoriamento#getPorta <em>Porta</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Porta</em>' attribute.
   * @see #getPorta()
   * @generated
   */
  void setPorta(int value);

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * The literals are from the enumeration {@link br.edu.utfpr.fb.oiArduBot.TipoPorta}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see br.edu.utfpr.fb.oiArduBot.TipoPorta
   * @see #setTipo(TipoPorta)
   * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage#getSensoriamento_Tipo()
   * @model
   * @generated
   */
  TipoPorta getTipo();

  /**
   * Sets the value of the '{@link br.edu.utfpr.fb.oiArduBot.Sensoriamento#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see br.edu.utfpr.fb.oiArduBot.TipoPorta
   * @see #getTipo()
   * @generated
   */
  void setTipo(TipoPorta value);

} // Sensoriamento
