/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OiArdubotUiModule extends AbstractOiArdubotUiModule {

	public OiArdubotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
