/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.oiardubot;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OiArdubotRuntimeModule extends AbstractOiArdubotRuntimeModule {
}
