/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OiArduBotRuntimeModule extends AbstractOiArduBotRuntimeModule {
}
