/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.oiArduBot.util;

import br.edu.utfpr.fb.oiArduBot.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see br.edu.utfpr.fb.oiArduBot.OiArduBotPackage
 * @generated
 */
public class OiArduBotSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static OiArduBotPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OiArduBotSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = OiArduBotPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case OiArduBotPackage.MODEL:
      {
        Model model = (Model)theEObject;
        T result = caseModel(model);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.CODIGO:
      {
        Codigo codigo = (Codigo)theEObject;
        T result = caseCodigo(codigo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.VARIAVEL:
      {
        Variavel variavel = (Variavel)theEObject;
        T result = caseVariavel(variavel);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.CONTROLE:
      {
        Controle controle = (Controle)theEObject;
        T result = caseControle(controle);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.PARA:
      {
        Para para = (Para)theEObject;
        T result = casePara(para);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.SE:
      {
        Se se = (Se)theEObject;
        T result = caseSe(se);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.SENAO:
      {
        Senao senao = (Senao)theEObject;
        T result = caseSenao(senao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.ROBO:
      {
        Robo robo = (Robo)theEObject;
        T result = caseRobo(robo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.SENSORIAMENTO:
      {
        Sensoriamento sensoriamento = (Sensoriamento)theEObject;
        T result = caseSensoriamento(sensoriamento);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.ATUACAO:
      {
        Atuacao atuacao = (Atuacao)theEObject;
        T result = caseAtuacao(atuacao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.NOTIFICACAO:
      {
        Notificacao notificacao = (Notificacao)theEObject;
        T result = caseNotificacao(notificacao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case OiArduBotPackage.BEEP:
      {
        Beep beep = (Beep)theEObject;
        T result = caseBeep(beep);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Model</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseModel(Model object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Codigo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Codigo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCodigo(Codigo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Variavel</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Variavel</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseVariavel(Variavel object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Controle</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Controle</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseControle(Controle object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Para</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Para</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePara(Para object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Se</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Se</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSe(Se object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Senao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Senao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSenao(Senao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Robo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Robo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRobo(Robo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sensoriamento</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sensoriamento</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSensoriamento(Sensoriamento object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Atuacao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Atuacao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAtuacao(Atuacao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Notificacao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Notificacao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNotificacao(Notificacao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Beep</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Beep</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBeep(Beep object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //OiArduBotSwitch
