/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.ui.tests;

import br.edu.utfpr.fb.OiArduBot.ui.internal.OiArduBotActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class OiArduBotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return OiArduBotActivator.getInstance().getInjector("br.edu.utfpr.fb.OiArduBot");
	}

}
