/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OiArduBotUiModule extends AbstractOiArduBotUiModule {

	public OiArduBotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
