/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.ide;

import br.edu.utfpr.fb.OiArduBotRuntimeModule;
import br.edu.utfpr.fb.OiArduBotStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OiArduBotIdeSetup extends OiArduBotStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OiArduBotRuntimeModule(), new OiArduBotIdeModule()));
	}
	
}
