/**
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.oiArduBot.impl;

import br.edu.utfpr.fb.oiArduBot.OiArduBotPackage;
import br.edu.utfpr.fb.oiArduBot.Senao;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Senao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.edu.utfpr.fb.oiArduBot.impl.SenaoImpl#getCodigoSenao <em>Codigo Senao</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SenaoImpl extends MinimalEObjectImpl.Container implements Senao
{
  /**
   * The default value of the '{@link #getCodigoSenao() <em>Codigo Senao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodigoSenao()
   * @generated
   * @ordered
   */
  protected static final String CODIGO_SENAO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodigoSenao() <em>Codigo Senao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodigoSenao()
   * @generated
   * @ordered
   */
  protected String codigoSenao = CODIGO_SENAO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SenaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OiArduBotPackage.Literals.SENAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodigoSenao()
  {
    return codigoSenao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodigoSenao(String newCodigoSenao)
  {
    String oldCodigoSenao = codigoSenao;
    codigoSenao = newCodigoSenao;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OiArduBotPackage.SENAO__CODIGO_SENAO, oldCodigoSenao, codigoSenao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OiArduBotPackage.SENAO__CODIGO_SENAO:
        return getCodigoSenao();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OiArduBotPackage.SENAO__CODIGO_SENAO:
        setCodigoSenao((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OiArduBotPackage.SENAO__CODIGO_SENAO:
        setCodigoSenao(CODIGO_SENAO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OiArduBotPackage.SENAO__CODIGO_SENAO:
        return CODIGO_SENAO_EDEFAULT == null ? codigoSenao != null : !CODIGO_SENAO_EDEFAULT.equals(codigoSenao);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (codigoSenao: ");
    result.append(codigoSenao);
    result.append(')');
    return result.toString();
  }

} //SenaoImpl
