/*
 * generated by Xtext 2.25.0
 */
package br.edu.utfpr.fb.ui;

import br.edu.utfpr.fb.OiArduBot.ui.internal.OiArduBotActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OiArduBotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(OiArduBotActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		OiArduBotActivator activator = OiArduBotActivator.getInstance();
		return activator != null ? activator.getInjector(OiArduBotActivator.BR_EDU_UTFPR_FB_OIARDUBOT) : null;
	}

}
